// Copyright (c) 2026 Robert G. Patterson
// SPDX-License-Identifier: MIT
//
// Generated by scripts/generate_embedded_defaults.py. Do not edit.
// Input: resources/defaults/finale27-macos-new-document-without-libraries.enigmaxml.gz
// SHA-256: c58e69ab810451f7b295b3fe1e5545f9e1dd9d064b10e84c9253fe7a90a1ff66
// Input: resources/defaults/finale27-windows-new-document-without-libraries.enigmaxml.gz
// SHA-256: 745444c37c44c13b17c72e1c6aad9f05e3e04ac2ab04bce027a2f55850201a5f

#pragma once

#include <cstddef>
#include <cstdint>

namespace finale_mus_reader {
namespace generated {

extern const std::uint8_t macosDefaultGzip[];
extern const std::size_t macosDefaultGzipSize;

extern const std::uint8_t windowsDefaultGzip[];
extern const std::size_t windowsDefaultGzipSize;

} // namespace generated
} // namespace finale_mus_reader
