// Copyright (c) 2026 Robert G. Patterson
// SPDX-License-Identifier: MIT
//
// Generated by scripts/generate_embedded_defaults.py. Do not edit.
// Input: resources/defaults/finale27-macos-new-document-without-libraries.enigmaxml.gz
// SHA-256: c58e69ab810451f7b295b3fe1e5545f9e1dd9d064b10e84c9253fe7a90a1ff66

#pragma once

#include <cstddef>
#include <cstdint>

namespace finale_mus_reader {
namespace generated {

extern const std::uint8_t macosDefaultGzip[];
extern const std::size_t macosDefaultGzipSize;

} // namespace generated
} // namespace finale_mus_reader
