#!/usr/bin/env python3
"""Generate the committed C++ representation of the bundled Finale defaults."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import hashlib
from pathlib import Path
import sys


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
HEADER_PATH = REPOSITORY_ROOT / "src/defaults/embedded_default.h"
SOURCE_PATH = REPOSITORY_ROOT / "src/defaults/embedded_default.cpp"


@dataclass(frozen=True)
class Baseline:
    """One pinned Finale 27 platform baseline."""

    symbol: str
    label: str
    sha256: str

    @property
    def path(self) -> Path:
        return REPOSITORY_ROOT / "resources/defaults" / self.label


BASELINES = (
    Baseline(
        symbol="macosDefaultGzip",
        label="finale27-macos-new-document-without-libraries.enigmaxml.gz",
        sha256="c58e69ab810451f7b295b3fe1e5545f9e1dd9d064b10e84c9253fe7a90a1ff66",
    ),
    Baseline(
        symbol="windowsDefaultGzip",
        label="finale27-windows-new-document-without-libraries.enigmaxml.gz",
        sha256="745444c37c44c13b17c72e1c6aad9f05e3e04ac2ab04bce027a2f55850201a5f",
    ),
)


def renderProvenance() -> str:
    lines = []
    for baseline in BASELINES:
        lines.append(f"// Input: resources/defaults/{baseline.label}")
        lines.append(f"// SHA-256: {baseline.sha256}")
    return "\n".join(lines)


def renderHeader() -> str:
    declarations = "\n\n".join(
        f"extern const std::uint8_t {baseline.symbol}[];\n"
        f"extern const std::size_t {baseline.symbol}Size;"
        for baseline in BASELINES
    )

    return f"""// Copyright (c) 2026 Robert G. Patterson
// SPDX-License-Identifier: MIT
//
// Generated by scripts/generate_embedded_defaults.py. Do not edit.
{renderProvenance()}

#pragma once

#include <cstddef>
#include <cstdint>

namespace finale_mus_reader {{
namespace generated {{

{declarations}

}} // namespace generated
}} // namespace finale_mus_reader
"""


def renderArray(baseline: Baseline, data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 12):
        values = ", ".join(f"0x{value:02x}" for value in data[offset : offset + 12])
        rows.append(f"    {values},")
    byteRows = "\n".join(rows)

    return (
        f"const std::uint8_t {baseline.symbol}[] = {{\n"
        f"{byteRows}\n"
        f"}};\n\n"
        f"const std::size_t {baseline.symbol}Size = sizeof({baseline.symbol});"
    )


def renderSource(payloads: dict[str, bytes]) -> str:
    arrays = "\n\n".join(
        renderArray(baseline, payloads[baseline.symbol]) for baseline in BASELINES
    )

    return f"""// Copyright (c) 2026 Robert G. Patterson
// SPDX-License-Identifier: MIT
//
// Generated by scripts/generate_embedded_defaults.py. Do not edit.
{renderProvenance()}

#include "defaults/embedded_default.h"

namespace finale_mus_reader {{
namespace generated {{

{arrays}

}} // namespace generated
}} // namespace finale_mus_reader
"""


def readBaseline(baseline: Baseline) -> bytes:
    data = baseline.path.read_bytes()
    actualHash = hashlib.sha256(data).hexdigest()
    if actualHash != baseline.sha256:
        raise RuntimeError(
            f"Unexpected SHA-256 for {baseline.path}: {actualHash}; "
            f"expected {baseline.sha256}"
        )
    return data


def updateFile(path: Path, expected: str, checkOnly: bool) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    if actual == expected:
        return True
    if checkOnly:
        print(f"stale generated file: {path.relative_to(REPOSITORY_ROOT)}", file=sys.stderr)
        return False
    path.write_text(expected, encoding="utf-8", newline="\n")
    print(f"generated {path.relative_to(REPOSITORY_ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report stale generated files without changing them",
    )
    args = parser.parse_args()

    payloads = {baseline.symbol: readBaseline(baseline) for baseline in BASELINES}
    outputs = (
        (HEADER_PATH, renderHeader()),
        (SOURCE_PATH, renderSource(payloads)),
    )
    results = [updateFile(path, expected, args.check) for path, expected in outputs]
    current = all(results)
    return 0 if current else 1


if __name__ == "__main__":
    sys.exit(main())
