#!/usr/bin/env python3
"""Write a recovery_coverage_probe corpus TSV from one survey's corpus_locations.csv.

Every row in corpus_locations.csv already names a loose, readable source path -- archive
members are tracked separately, in archive_locations.csv, and are not probe input -- so this
is a straight projection to corpus_id<TAB>source_path, plus the `#root:`/`#companion:`
header lines recovery_coverage_probe.cpp reads (see readCorpusRows() there) so a FAILED
line can show a path relative to the corpus and a row can be compared against its Finale 27
companion, without either convention being repeated on every row. `#companion:` may be
written more than once, for a corpus whose companion-naming convention changed partway
through (rpatters1-main: older sources pair under `-exports`/`.fin27.musx`, more recent ones
under `-finale27`/`.musx`) -- see --companion below.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("corpus_locations_csv", type=Path)
    parser.add_argument("--survey", required=True, help="survey id, for the header comment")
    parser.add_argument("--root", required=True, help="this corpus's CORPUS_ROOT")
    parser.add_argument("--companion", action="append", default=[], metavar="'DIR SUFFIX'",
        help="one companion-naming convention, as a single argument formatted "
            "'<dir-name> <suffix>' (EXPORT_DIR_NAME and EXPORT_SUFFIX, space-joined -- kept "
            "as one argument rather than two so a dir-name like -finale27 is never read as "
            "another flag). Repeat for a corpus whose convention changed over time (tried "
            "in the order given, first match on disk wins -- see "
            "recovery_coverage_probe.cpp's companionPathFor()). Omit entirely when the "
            "corpus has no companions (HAS_EXPORTS=0)")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    with args.corpus_locations_csv.open(newline="", encoding="utf-8") as handle:
        rows = [row for row in csv.DictReader(handle) if row.get("source_path")]

    with args.output.open("w", encoding="utf-8") as out:
        out.write(f"# recovery_coverage_probe corpus list -- {args.survey} "
            f"({len(rows)} files).\n")
        out.write("#\n")
        out.write("# corpus_id<TAB>source_path per line; blank lines and '#' comment "
            "lines are\n")
        out.write("# skipped by the probe.\n")
        out.write("#\n")
        out.write("# Generated by private/regenerate.sh (scripts/generate_probe_corpus.py) "
            "from\n")
        out.write(f"# {args.corpus_locations_csv}; do not hand-edit, rerun "
            "regenerate.sh instead.\n")
        out.write(f"#root: {args.root}\n")
        for companion in args.companion:
            out.write(f"#companion: {companion}\n")
        out.write("\n")
        for row in rows:
            out.write(f"{row['corpus_id']}\t{row['source_path']}\n")


if __name__ == "__main__":
    main()
