#!/usr/bin/env python3
"""Generate the committed C++ representation of the bundled Finale default."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
INPUT_PATH = REPOSITORY_ROOT / (
    "resources/defaults/"
    "finale27-macos-new-document-without-libraries.enigmaxml.gz"
)
HEADER_PATH = REPOSITORY_ROOT / "src/defaults/embedded_default.h"
SOURCE_PATH = REPOSITORY_ROOT / "src/defaults/embedded_default.cpp"
EXPECTED_SHA256 = "c58e69ab810451f7b295b3fe1e5545f9e1dd9d064b10e84c9253fe7a90a1ff66"
INPUT_LABEL = "finale27-macos-new-document-without-libraries.enigmaxml.gz"


def renderHeader() -> str:
    return f"""// Copyright (c) 2026 Robert G. Patterson
// SPDX-License-Identifier: MIT
//
// Generated by scripts/generate_embedded_defaults.py. Do not edit.
// Input: resources/defaults/{INPUT_LABEL}
// SHA-256: {EXPECTED_SHA256}

#pragma once

#include <cstddef>
#include <cstdint>

namespace finale_mus_reader {{
namespace generated {{

extern const std::uint8_t macosDefaultGzip[];
extern const std::size_t macosDefaultGzipSize;

}} // namespace generated
}} // namespace finale_mus_reader
"""


def renderSource(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 12):
        values = ", ".join(f"0x{value:02x}" for value in data[offset : offset + 12])
        rows.append(f"    {values},")
    byteRows = "\n".join(rows)

    return f"""// Copyright (c) 2026 Robert G. Patterson
// SPDX-License-Identifier: MIT
//
// Generated by scripts/generate_embedded_defaults.py. Do not edit.
// Input: resources/defaults/{INPUT_LABEL}
// SHA-256: {EXPECTED_SHA256}

#include "defaults/embedded_default.h"

namespace finale_mus_reader {{
namespace generated {{

const std::uint8_t macosDefaultGzip[] = {{
{byteRows}
}};

const std::size_t macosDefaultGzipSize = sizeof(macosDefaultGzip);

}} // namespace generated
}} // namespace finale_mus_reader
"""


def verifyInput(data: bytes) -> None:
    actualHash = hashlib.sha256(data).hexdigest()
    if actualHash != EXPECTED_SHA256:
        raise RuntimeError(
            f"Unexpected SHA-256 for {INPUT_PATH}: {actualHash}; "
            f"expected {EXPECTED_SHA256}"
        )


def updateFile(path: Path, expected: str, checkOnly: bool) -> bool:
    actual = path.read_text(encoding="utf-8") if path.exists() else None
    if actual == expected:
        return True
    if checkOnly:
        print(f"stale generated file: {path.relative_to(REPOSITORY_ROOT)}", file=sys.stderr)
        return False
    path.write_text(expected, encoding="utf-8", newline="\n")
    print(f"generated {path.relative_to(REPOSITORY_ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="report stale generated files without changing them",
    )
    args = parser.parse_args()

    data = INPUT_PATH.read_bytes()
    verifyInput(data)
    outputs = (
        (HEADER_PATH, renderHeader()),
        (SOURCE_PATH, renderSource(data)),
    )
    results = [updateFile(path, expected, args.check) for path, expected in outputs]
    current = all(results)
    return 0 if current else 1


if __name__ == "__main__":
    sys.exit(main())
